spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ataccama?useSSL=false
    username: root
    password: root

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create-drop